# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :otuslinux => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.101',
	:disks => {
		:sata1 => {
			:dfile => './sata1.vdi',
			:size => 3000,
			:port => 1
		},
		:sata2 => {
                        :dfile => './sata2.vdi',
                        :size => 3000, # Megabytes
			:port => 2
		},
                :sata3 => {
                        :dfile => './sata3.vdi',
                        :size => 3000,
                        :port => 3
                },
                :sata4 => {
                        :dfile => './sata4.vdi',
                        :size => 3000, # Megabytes
                        :port => 4
                }

	
  },
}
}
Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            	  vb.customize ["modifyvm", :id, "--memory", "1024"]
		  vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]
		vb.customize ['createhd', '--filename', './ide2.vdi', '--variant', 'Standard', '--size', '40960']
		vb.customize ['storageattach', :id,  '--storagectl', 'IDE', '--port', '1', '--device', 0, '--type', 'hdd', '--medium', './ide2.vdi']
		  boxconfig[:disks].each do |dname, dconf|
			  unless File.exist?(dconf[:dfile])
				vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
			  end
			  vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]

		  end
		  end
		  
		        
 	  box.vm.provision "shell", inline: <<-SHELL
	      mkdir -p ~root/.ssh
              cp ~vagrant/.ssh/auth* ~root/.ssh
	      yum install -y mdadm smartmontools hdparm gdisk
		  mdadm --zero-superblock /dev/sd{c,d,e,f}
		  mdadm --create /dev/md0 -l5 -n 4 /dev/sd{c,d,e,f}
		  sgdisk -o /dev/md0
		  sgdisk -n 1:2048:150000 -n 2:150001:287000 -n 3:287001:391000 -n 4:391001:800000 -n 5:800001:1400000 /dev/md0
		  mkfs.ext4 /dev/md0p1
		  mkfs.ext4 /dev/md0p2
		  mkfs.ext4 /dev/md0p3
		  mkfs.ext4 /dev/md0p4
		  mkfs.ext4 /dev/md0p5
		  mkdir -p /part1 /part2 /part3 /part4 /part5
		  mount /dev/md0p1 /part1
		  mount /dev/md0p2 /part2
		  mount /dev/md0p3 /part3
		  mount /dev/md0p4 /part4
		  mount /dev/md0p5 /part5
		  mdadm --examine --scan --config=mdadm.conf >> /etc/mdadm.conf
  	  SHELL

      end
  end
end

